
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>Verdant</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Localization\en-US\Mods.Verdant.Origins.hjson" />
    <None Remove="Localization\en-US_Mods.Verdant.MusicDisplay.hjson" />
    <None Remove="Localization\en-US_Mods.Verdant.SetBonuses.hjson" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="NetEasy">
      <HintPath>lib\NetEasy_v0.1.8.dll</HintPath>
    </Reference>
    <Reference Include="NPCUtils">
      <HintPath>lib\NPCUtils.dll</HintPath>
    </Reference>
    <Reference Include="StockableShops">
      <HintPath>lib\StockableShops.dll</HintPath>
    </Reference>
    <Reference Include="StructureHelper">
      <HintPath>lib\StructureHelper.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Systems\ModCompat\Textures\" />
    <Folder Include="Systems\PestControl\Textures\" />
  </ItemGroup>
</Project>